services:
  server:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql:5.7.33
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    networks:
      - app-network
    volumes:
      - ./docker/dbdata:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DRIVER: server
      ADMINER_DEFAULT_USER: $DB_DATABASE
      ADMINER_DEFAULT_PASSWORD: $DB_PASSWORD
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - db

  php:
    build: .
    image: jojo-8.3
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./backend:/var/www
  
  schedule:
    build: .
    image: jojo-8.3
    restart: unless-stopped
    user: www-data
    networks:
      - app-network
    volumes:
      - ./backend:/var/www
    command: 
      - /bin/sh
      - -c
      - |
        php artisan cache:clear
        php artisan schedule:clear-cache
        php artisan schedule:work

networks:
  app-network:
    driver: bridge