name: Check Frontend Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: read

jobs:
  frontend-build-full:
    name: Construir proyecto frontend con Vite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./frontend

      - name: Instalar dependencias
        working-directory: ./frontend
        run: npm ci

      - name: Construir proyecto Vite
        working-directory: ./frontend
        run: npm run build
        # env: 
        #   VITE_REVERB_APP_KEY: ${{ secrets.ENV_REVERB_KEY }}
        #   VITE_VERSION_APP: ${{ github.ref_name }}