name: PR checks (filtrado por rama)

on:
  workflow_dispatch: {}                # permite ejecutar manualmente desde Actions -> Run workflow
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - next

  pull_request_review:
    types: [submitted]

permissions:
  contents: read

jobs:
  php-tests-full:
    name: Ejecutar php artisan test
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'next' }}
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: sqlite
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Copy .env
        working-directory: ./laravel
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
          
      - name: Instalar dependencias
        working-directory: ./laravel
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Preparar entorno
        run: |
          cp .env.example .env || true
          php artisan key:generate

      - name: Crear base de datos SQLite
        working-directory: ./laravel
        run: |
          mkdir -p database
          touch database/database.sqlite
      
      - name: Link storage
        working-directory: ./laravel
        run: php artisan storage:link

      - name: Ejecutar pruebas con php artisan test
        working-directory: ./laravel
        env:
          DB_DATABASE: database/database.sqlite
        run: php artisan test

  frontend-build-full:
    name: Construir proyecto frontend con Vite
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'next' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./frontend

      - name: Instalar dependencias
        working-directory: ./frontend
        run: npm install

      - name: Construir proyecto Vite
        working-directory: ./frontend
        run: npm run build
        # env: 
        #   VITE_REVERB_APP_KEY: ${{ secrets.ENV_REVERB_KEY }}
        #   VITE_VERSION_APP: ${{ github.ref_name }}